export default {
  login: "KoushikwebDev",
  id: 98579822,
  node_id: "U_kgDOBeA1bg",
  avatar_url: "https://avatars.githubusercontent.com/u/98579822?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/KoushikwebDev",
  html_url: "https://github.com/KoushikwebDev",
  followers_url: "https://api.github.com/users/KoushikwebDev/followers",
  following_url:
    "https://api.github.com/users/KoushikwebDev/following{/other_user}",
  gists_url: "https://api.github.com/users/KoushikwebDev/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/KoushikwebDev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/KoushikwebDev/subscriptions",
  organizations_url: "https://api.github.com/users/KoushikwebDev/orgs",
  repos_url: "https://api.github.com/users/KoushikwebDev/repos",
  events_url: "https://api.github.com/users/KoushikwebDev/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/KoushikwebDev/received_events",
  type: "User",
  site_admin: false,
  name: "Koushik Saha",
  company: "HelloCompany",
  blog: "http://ksaha.netlify.app/",
  location: "Kolkata",
  email: null,
  hireable: null,
  bio: "MERN stack dev passionate about building efficient web apps. Always learning & expanding my skills. Delivering clean code for a great user experience.",
  twitter_username: null,
  public_repos: 163,
  public_gists: 34,
  followers: 2345,
  following: 113,
  created_at: "2022-01-28T07:36:42Z",
  updated_at: "2023-01-15T12:06:56Z",
};
